version: '2.2'
services:
  mysql8:
    container_name: mysql8
    image: mysql/mysql-server:8.0.23
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    volumes:
      - "~/conf/mysql8/conf.d:/etc/mysql/conf.d"
      - "~/conf/mysql8/data:/var/lib/mysql"
      - "~/mysql8/init:/docker-entrypoint-initdb.d/"
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "~/redis8/data:/data"
      - "~/conf/redis8/redis.conf:/etc/redis/redis.conf"
    command: "redis-server /etc/redis/redis.conf --appendonly yes"
  product_gzh:
    container_name: product_gzh
    image: mp-wx-spider:latest
    volumes:
      - "~/data/wx:/app/output"
      - "~/data/wx/conf:/app/conf"
      - "~/data/wx/log:/app/log"
    command: "/bin/bash bin/product_gzh.sh"
    networks:
      - default
      - wx_app_net
    external_links:
      - mysql8
      - redis
    depends_on:
      - mysql8
      - redis
  consume_gzh:
    container_name: consume_gzh
    image: mp-wx-spider:latest
    volumes:
      - "~/data/wx:/app/output"
      - "~/data/wx/conf:/app/conf"
      - "~/data/wx/log:/app/log"
    command: "/bin/bash bin/consume_gzh.sh"
    networks:
      - default
      - wx_app_net
    external_links:
      - mysql8
      - redis
    depends_on:
      - product_gzh
  consume_article:
    container_name: consume_article
    image: mp-wx-spider:latest
    volumes:
      - "~/data/wx:/app/output"
      - "~/data/wx/conf:/app/conf"
      - "~/data/wx/log:/app/log"
    command: "/bin/bash bin/consume_article.sh"
    networks:
      - default
      - wx_app_net
    external_links:
      - mysql8
      - redis
    depends_on:
      - consume_gzh
networks:
  wx_app_net:
    external: true
